#!/bin/bash

#Usage: enc_dec.sh <enc|dec> <filename>

read -r ENC_KEY < /root/encr/.enc.key
read -r TOTP_SEC < /root/encr/.totp.secret

#Code generated by Authenticator app
VALID_CODE=$(oathtool --totp -b "$TOTP_SEC")

# Check the user totp
echo "Please Enter the onetime user code: "
read -r USER_CODE


if [ "$USER_CODE" != "$VALID_CODE" ]; then
	echo "Invalid Code"
	exit 1
fi

#Crypto Operations
if [ "$1" = "enc" ]; then
	openssl enc -aes256 -pbkdf2 -in "$2" -out "$2.enc" -pass pass:$ENC_KEY
	echo "Encryption Successfull"
elif [ "$1" = "dec" ]; then
	openssl enc -aes256 -d  -pbkdf2 -in "$2" -out "${2::-4}" -pass pass:$ENC_KEY
	echo "Decryption Successfull"
fi
